### ISSUE TITLE
Error: Evaluation failed: TestingLibraryElementError: Unable to find an accessible element with the role "button"

### ISSUE THREAD

**Issue by benjamin-carriou** [scaleway/scaleway-ui#2195]
Hi,

I'am trying to reuse the storybook in my project but when i push the code on codemagic with the following command:

`npx chromatic --project-token=1a5d[...] --build-script-name=build:storybook --allow-console-errors`

An error appears:

```
Chromatic CLI v6.14.0
https://www.chromatic.com/docs/cli

  ✔ Authenticated with Chromatic
    → Using project token '********5491'
  ✔ Retrieved git information
    → Commit 'bec27bf' on branch 'main'; found 1 parent build
  ✔ Collected Storybook metadata
    → ; no supported addons found
  ✔ Initialized build
    → Build 6 initialized
  ✔ Storybook built in 4 minutes 31 seconds
    → View build log at /root/scaleway-ui/build-storybook.log
  ✔ Publish complete in 45 seconds
    → View your Storybook at https://63bebe8ce693f446618df4b5-zhrkhnbyvw.chromatic.com
  ✔ Started build 6
    → Continue setup at https://www.chromatic.com/setup?appId=63bebe8ce693f446618df4b5
  ✔ Build 6 failed after 37 seconds
    → Tested 413 stories across 82 components; captured 413 snapshots and found 1 component error
```

This is the content of the error:

```
Error: Evaluation failed: TestingLibraryElementError: Unable to find an accessible element with the role "button"

Here are the accessible roles:

  combobox:

  Name "Select...":
  <input
    aria-autocomplete="list"
    aria-expanded="false"
    aria-haspopup="true"
    autocapitalize="none"
    autocomplete="off"
    autocorrect="off"
    class=""
    id=":r0:"
    role="combobox"
    spellcheck="false"
    style="color: inherit; background: 0px center; opacity: 1; width: 100%; grid-area: 1 / 2 / auto / auto; font: inherit; min-width: 2px; border: 0px; margin: 0px; outline: 0px; padding: 0px;"
    tabindex="0"
    type="text"
    value=""
  />

  --------------------------------------------------

Ignored nodes: comments, script, style
<body
  class="sb-main-padded sb-show-main"
>
  <div
    class="sb-preparing-story sb-wrapper"
  >
    <div
      class="sb-loader"
    />
  </div>
  <div
    class="sb-preparing-docs sb-wrapper"
  >
    <div
      class="sb-previewBlock"
    >
      <div
        class="sb-previewBlock_header"
      >
        <div
          class="sb-previewBlock_icon"
        />
        <div
          class="sb-previewBlock_icon"
        />
        <div
          class="sb-previewBlock_icon"
        />
        <div
          class="sb-previewBlock_icon"
        />
      </div>
      <div
        class="sb-previewBlock_body"
      >
        <div
          class="sb-loader"
        />
      </div>
    </div>
    <table
      aria-hidden="true"
      class="sb-argstableBlock"
    >
      <thead
        class="sb-argstableBlock-head"
      >
        <tr>
          <th>
            <span>
              Name
            </span>
          </th>
          <th>
            <span>
              Description
            </span>
          </th>
          <th>
            <span>
              Default
            </span>
          </th>
          <th>
            <span>
              Control
            </span>
          </th>
        </tr>
      </thead>
      <tbody
        class="sb-argstableBlock-body"
      >
        <tr>
          <td>
            <span>
              propertyName
            </span>
            <span
              title="Required"
            >
              *
            </span>
          </td>
          <td>
            <div>
              <span>
                This is a short description
              </span>
            </div>
            <div
              class="sb-argstableBlock-summary"
            >
              <div>
                <span
                  class="sb-argstableBlock-code"
                >
                  summary
                </span>
              </div>
            </div>
          </td>
          <td>
            <div>
              <span
                class="sb-argstableBlock-code"
              >
                defaultValue
              </span>
            </div>
          </td>
          <td>
            <button>
              Set string
            </button>
          </td>
        </tr>
        <tr>
          <td>
            <span>
              propertyName
            </span>
            <span>
              *
            </span>
          </td>
          <td>
            <div>
              <span>
                This is a short description
              </span>
            </div>
            <div
              class="sb-argstableBlock-summary"
            >
              <div>
                <span
                  class="sb-argstableBlock-code"
                >
                  summary
                </span>
              </div>
            </div>
          </td>
          <td>
            <div>
              <span
                class="sb-argstableBlock-code"
              >
                defaultValue
              </span>
            </div>
          </td>
          <td>
            <button>
              Set string
            </button>
          </td>
        </tr>
        <tr>
          <td>
            <span>
              propertyName
            </span>
            <span>
              *
            </span>
          </td>
          <td>
            <div>
              <span>
                This is a short description
              </span>
            </div>
            <div
              class="sb-argstableBlock-summary"
            >
              <div>
                <span
                  class="sb-argstableBlock-code"
                >
                  summary
                </span>
              </div>
            </div>
          </td>
          <td>
            <div>
              <span
                class="sb-argstableBlock-code"
              >
                defaultValue
              </span>
            </div>
          </td>
          <td>
            <button>
              Set string
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div
    class="sb-nopreview sb-wrapper"
  >
    <div
      class="sb-nopreview_main"
    >
      <h1
        class="sb-nopreview_heading sb-heading"
      >
        No Preview
      </h1>
      <p>
        Sorry, but you either have no stories or none are selected somehow.
      </p>
      <ul>
        <li>
          Please check the Storybook config.
        </li>
        <li>
          Try reloading the page.
        </li>
      </ul>
      <p>
        If the problem persists, check the browser console, or the terminal you've run Storybook from.
      </p>
    </div>
  </div>
  <div
    class="sb-errordisplay sb-wrapper"
  >
    <pre
      class="sb-heading"
      id="error-message"
    />
    <pre
      class="sb-errordisplay_code"
    >
      <code
        id="error-stack"
      />
    </pre>
  </div>
  <div
    id="root"
  >
    <div
      style="margin-bottom: 150px;"
    >
      <div
        style="height: 80px;"
      >
        <div
          class=" css-1t0vhyn-container e1lzna4r5"
          data-testid="rich-select-basic"
        >
          <span
            class="css-7pg0cj-a11yText"
            id="react-select-2-live-region"
          />
          <span
            aria-atomic="false"
            aria-live="polite"
            aria-relevant="additions text"
            class="css-7pg0cj-a11yText"
          />
          <div
            class=" css-rjf8lv-control"
          >
            <div
              class=" css-qm2nwd"
            >
              <label
                aria-live="assertive"
                as="label"
                class="css-isgbik e1lzna4r2"
                for=":r0:"
              >
                Select...
              </label>
              <div
                class=" css-19ckjwh-singleValue"
              >
                Option A
              </div>
              <div
                class="css-7ygvwy"
                data-value=""
              >
                <input
                  aria-autocomplete="list"
                  aria-expanded="false"
                  aria-haspopup="true"
                  autocapitalize="none"
                  autocomplete="off"
                  autocorrect="off"
                  class=""
                  id=":r0:"
                  role="combobox"
                  spellcheck="false"
                  style="color: inherit; background: 0px center; opacity: 1; width: 100%; grid-area: 1 / 2 / auto / auto; font: inherit; min-width: 2px; border: 0px; margin: 0px; outline: 0px; padding: 0px;"
                  tabindex="0"
                  type="text"
                  value=""
                />
              </div>
            </div>
            <div
              class=" css-ffo8u1"
            >
              <span
                class=" css-1rlboq6-indicatorSeparator"
              />
              <div
                aria-hidden="true"
                class=" css-1xc3v61-indicatorContainer"
              >
                <div
                  class="css-108jn5w e1sgck4o0"
                >
                  <svg
                    class="css-klb7kl etwatq50"
                    viewBox="0 0 16 16"
                  >
                    <path
                      d="M8 11c-.28 0-.55-.11-.74-.3L3.3 6.77a1.04 1.04 0 0 1 0-1.47 1.06 1.06 0 0 1 1.49 0L8 8.48l3.2-3.17a1.06 1.06 0 0 1 1.72.33 1.04 1.04 0 0 1-.23 1.14L8.74 10.7c-.2.2-.46.31-.74.31"
                    />
                  </svg>
                </div>
              </div>
            </div>
          </div>
          <input
            name="basic"
            type="hidden"
            value="a"
          />
          <div
            class="css-9vn1ol e1lzna4r3"
          >
            <div
              class="css-19pioxy e1lzna4r4"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
  <div
    hidden="true"
    id="docs-root"
  />
</body>
    at Object.getElementError (https://63bebe8ce693f446618df4b5-zhrkhnbyvw.capture.chromatic.com/75330.834ff524.iframe.bundle.js:2:1916496)
    at https://63bebe8ce693f446618df4b5-zhrkhnbyvw.capture.chromatic.com/75330.834ff524.iframe.bundle.js:2:1935143
    at https://63bebe8ce693f446618df4b5-zhrkhnbyvw.capture.chromatic.com/75330.834ff524.iframe.bundle.js:2:1934342
    at https://63bebe8ce693f446618df4b5-zhrkhnbyvw.capture.chromatic.com/75330.834ff524.iframe.bundle.js:2:1935683
    at Playground.play (https://63bebe8ce693f446618df4b5-zhrkhnbyvw.capture.chromatic.com/main.7e9be0db.iframe.bundle.js:1:660171)
    at _callee7$ (https://63bebe8ce693f446618df4b5-zhrkhnbyvw.capture.chromatic.com/75330.834ff524.iframe.bundle.js:2:1373312)
    at tryCatch (https://63bebe8ce693f446618df4b5-zhrkhnbyvw.capture.chromatic.com/75330.834ff524.iframe.bundle.js:2:4694795)
    at Generator.invoke (https://63bebe8ce693f446618df4b5-zhrkhnbyvw.capture.chromatic.com/75330.834ff524.iframe.bundle.js:2:4697342)
    at Generator.next (https://63bebe8ce693f446618df4b5-zhrkhnbyvw.capture.chromatic.com/75330.834ff524.iframe.bundle.js:2:4695570)
    at StoryRender_asyncGeneratorStep (https://63bebe8ce693f446618df4b5-zhrkhnbyvw.capture.chromatic.com/75330.834ff524.iframe.bundle.js:2:1365728)
    at ExecutionContext._evaluateInternal (/var/task/capture-v4/build/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/var/task/capture-v4/build/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async /var/task/capture-v4/build/bundle.js:703215:7
    at async NavigatorWatcher2.waitForIdle (/var/task/capture-v4/build/bundle.js:673194:9)
    at async PuppeteerRenderer.renderSpec (/var/task/capture-v4/build/bundle.js:703162:25)
    at async PuppeteerRenderer.renderSnapshot (/var/task/capture-v4/build/bundle.js:703054:21)
    at async PuppeteerRenderer.captureSpecs (/var/task/capture-v4/build/bundle.js:703003:18)
    at async PuppeteerRenderer.executeWithCallback (/var/task/capture-v4/build/bundle.js:703269:14)
```

A screen of element in error:

![image](https://user-images.githubusercontent.com/116572804/211865889-e74929ae-1110-4eec-8939-b29d24cfaf5d.png)

**Comment by matthprost** [comment]
Hello @benjamin-carriou,

It seems like chromatic is testing accessibility on our components and one is not passing the test (`RichSelect`) however the storybook is still built and available. The library is still unstable and some component are not perfect yet, explaining why the test is failing.

I don't really understand why this is blocking for your usage, could you give me more context?

In the meaning time I will check if I can fix this issue, and keep you in touch 🙏

**Comment by benjamin-carriou** [comment]
Hi @matthprost  and thx for the quick response :)

I had desactivate chromatic testing and I can host your storybook on now

In fact, I want to use your storybook in Figma with Locofy to drag and drop components on to accelerate our designs conceptions.

It is explain [here](https://www.youtube.com/watch?v=M847fk4KVSM) but we can't import them in Figma because 1 composant "crash".

Thx for your help :)

**Comment by matthprost** [comment]
Hi again @benjamin-carriou,

I found out the issue on our side, a selector was wrong in storybook play which was leading to this error.

We will merge and deploy very soon this fix, thank you for reporting it 🤝
