### ISSUE TITLE
Cloned and getting installation error

### ISSUE THREAD

**Issue by Junaid300** [scaleway/scaleway-ui#2212]
I cloned the project  added pnpm and run `pnpm install` command. It added all need decencies and then i ran `pnpm run start`. It throws an error.

My node version is `18.12.0`
pnpm version: `7.25.1`

I tried version 16 and 19 for node and it gives same error. For version shifting i am using nvm

```
Failed to load preset: {"type":"presets"} on level 1
ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of Object
ERR!     at new NodeError (node:internal/errors:393:5)
ERR!     at validateString (node:internal/validators:163:11)
ERR!     at Module.require (node:internal/modules/cjs/loader:1054:3)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR!     at interopRequireDefault (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:178:16)
ERR!     at getContent (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:194:10)
ERR!     at loadPreset (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:203:20)
ERR!     at /home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18)
ERR!     at loadPreset (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:225:81)
ERR!     at /home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18)
ERR!     at getPresets (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:313:23)
ERR!     at loadAllPresets (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:365:10)
ERR!     at buildDev (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-server@6.5.15_5icj5b5eayv74ugp47po7l6rpm/node_modules/@storybook/core-server/dist/cjs/build-dev.js:209:50)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!  TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of Object
ERR!     at new NodeError (node:internal/errors:393:5)
ERR!     at validateString (node:internal/validators:163:11)
ERR!     at Module.require (node:internal/modules/cjs/loader:1054:3)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR!     at interopRequireDefault (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:178:16)
ERR!     at getContent (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:194:10)
ERR!     at loadPreset (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:203:20)
ERR!     at /home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18)
ERR!     at loadPreset (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:225:81)
ERR!     at /home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18)
ERR!     at getPresets (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:313:23)
ERR!     at loadAllPresets (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-common@6.5.15_ezwbcwsuf2bqvxzlg3s7mwruqi/node_modules/@storybook/core-common/dist/cjs/presets.js:365:10)
ERR!     at buildDev (/home/junaidklair/github.com/scaleway-ui/node_modules/.pnpm/@storybook+core-server@6.5.15_5icj5b5eayv74ugp47po7l6rpm/node_modules/@storybook/core-server/dist/cjs/build-dev.js:209:50)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
ERR!   code: 'ERR_INVALID_ARG_TYPE'
ERR! }

```

**Comment by matthprost** [comment]
Hello @Junaid300!

Thank you for your issue, I'm trying to understand how you have this error and how to reproduce it.
First could you try to install node `v18.13.0` then to run the command `pnpm install && pnpm build`, tell me if it works.

> I cloned the project added pnpm and run pnpm install command. It added all need decencies and then i ran pnpm i. It throws an error.

I'm not sure what you mean, you made once `pnpm install` it worked, then you make `pnpm i` (which is same as `pnpm install`) and it failed?

**Comment by matthprost** [comment]
Hello 👋 

I have no news about this issue, I will close it but of course if you're still facing it don't hesitate to reopen it 😄
